### ISSUE TITLE
Django not picking up static files

### ISSUE THREAD

**Issue by paddyjoy** [mazelife/django-redactoreditor#2]
Hi,

Great project you have going here.

I'm not sure if this is a bug or a config problem on my side however when I install django-redactoreditor and add it to my installed apps django_staticfiles doesn't find the static files.

When running the development server no static files are served and when in deployment running "python manage.py collectstatic" doesn't copy the redactor static files to STATIC_ROOT.

Any ideas?

My setup is:
django 1.6
django-redactoreditor 1.2.7

**Comment by mazelife** [comment]
This was a bug in the setup.py script. That's addressed here: in this commit: 01ae1cdff4c01f1c8f31ee7676c756966b575396. I've also uploaded the new version to PyPI, so `pip install django-redactoreditor` should include the static files. Note that this is version 1.2.10 in PyPI, so if you already have 1.2.7 of django-redactoreditor installed, it's safe to upgrade to 1.2.10.
